In [1]:
# python zip explanation
l1 = [1,2,3]
l2 = [6,7,8]
list(zip(l1,l2))

[(1, 6), (2, 7), (3, 8)]

In [2]:
#using python list
import numpy as np
import time
size = 100
l1 = list(range(size))
l2 = list(range(size))
start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()
print(add[0:10])
print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.00021028518676757812


In [3]:
# using numpy arrays
import numpy as np
import time
size = 100
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))
start = time.time()
add = l1+l2
print(add[0:10])
end = time.time()
print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.002185821533203125


In [4]:
np.array([1,2,3,4,5,6])


array([1, 2, 3, 4, 5, 6])

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr = np.array(list[[12,3,456,89],[123,34,56,66]])
arr

array(list[[12, 3, 456, 89], [123, 34, 56, 66]], dtype=object)

In [7]:
arr = np.array([[12,3,456,89],[123,34,56,66]])
arr

array([[ 12,   3, 456,  89],
       [123,  34,  56,  66]])

In [8]:
type(arr)

numpy.ndarray

In [9]:
len(arr)

2

CREATING NUMPY ARRAY

In [10]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[23,45,678]])
arr3 = np.array([[10,20,30],[11,12,13],[20,21,22],[6,7,8],[45,55,78]])


In [11]:
print(f'the 1D array is = {arr1}')
print(f'the 2D array is = {arr2}')
print(f'the 3D array is = {arr3}')

the 1D array is = [1 2 3 4 5 6]
the 2D array is = [[  1   2   3]
 [ 23  45 678]]
the 3D array is = [[10 20 30]
 [11 12 13]
 [20 21 22]
 [ 6  7  8]
 [45 55 78]]


In [12]:
print(type(arr1))
print(type(arr2))
print(type(arr3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
2


In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [17]:
np.full((4,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [18]:
np.eye(4) # identy matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.eye(1)

array([[1.]])

In [20]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [21]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [22]:
np.arange(1,20,-1)

array([], dtype=int64)

In [23]:
np.arange(5,10,5)

array([5])

In [24]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

CHEAKING ARRAY PROPERTIES

In [25]:
arr1

array([1, 2, 3, 4, 5, 6])

In [26]:
arr2

array([[  1,   2,   3],
       [ 23,  45, 678]])

In [27]:
arr2.shape

(2, 3)

In [28]:
arr2.ndim

2

In [29]:
arr2.dtype

dtype('int64')

In [30]:
arr2.size

6

CHANGING DATATYPE

In [31]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [33]:
id(arr)

2552286477648

In [35]:
type(arr)

numpy.ndarray

In [38]:
arr = np.array([1,2,3],dtype = np.float32)
print(arr.dtype)


float32


In [39]:
arr_int = arr.astype(np.int32) # Convert float to int
print(arr_int) # [1 2 3]

[1 2 3]


In [40]:
arr1

array([1, 2, 3, 4, 5, 6])

In [42]:
a = np.array([[1,2,3],[33,45,67]])
a

array([[ 1,  2,  3],
       [33, 45, 67]])

In [45]:
np.shape(a)

(2, 3)

In [47]:
np.ndim(a)

2

In [50]:
np.size(a)

6

RESIZE AND FLATTING ARRAY

In [51]:
a

array([[ 1,  2,  3],
       [33, 45, 67]])

In [53]:
a.shape

(2, 3)

In [57]:
reshaped = a.reshape((3,2))
print(reshaped)

[[ 1  2]
 [ 3 33]
 [45 67]]


In [58]:
b = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
b.shape

(3, 4)

In [66]:
reshaped = b.reshape((2,6))
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [65]:
c = np.array([[a,b,c],[d,e,f],[g,h,i]])
c

NameError: name 'c' is not defined

In [67]:
a

array([[ 1,  2,  3],
       [33, 45, 67]])

In [69]:
c  = np.array([[1.2,2.3,2.5],[12.3,23.5,98.4]])
c


array([[ 1.2,  2.3,  2.5],
       [12.3, 23.5, 98.4]])

In [70]:
c.shape

(2, 3)

In [72]:
reversed = c.reshape((3,2))
reversed

array([[ 1.2,  2.3],
       [ 2.5, 12.3],
       [23.5, 98.4]])

INDEXING AND SLICING

In [73]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
b[0]

array([1, 2, 3, 4])

In [75]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [76]:
arr1[2]

np.int64(3)

In [77]:
arr1[-1]

np.int64(7)

In [78]:
arr1[1:4]

array([2, 3, 4])

In [80]:
hex(16)

'0x10'

In [81]:
16 ^ 23

7

In [82]:
a = 3
b = 5

In [84]:
a,b = b,a
print(a)
print(b)

3
5


In [85]:
temp = a
a = b
b = temp

In [93]:
print(a)
print(b)

5
3


In [88]:
bin(10)

'0b1010'

In [89]:
bin(11)

'0b1011'

In [91]:
print(0b1010)

10


In [92]:
~45

-46

In [94]:
b

3

In [95]:
a = input()

 fhe


In [102]:
x = int(input('enter the 1st no'))
y = int(input('enter the 2nd no'))
devide = x**y
print(devide)

enter the 1st no 34
enter the 2nd no 45


825184889837725994971915471173621692744697928074424045623011467853824
