In [1]:
import numpy as np
np.__version__


'2.3.2'

In [2]:
mylist = [0,1,2,3,4,5]
mylist

[0, 1, 2, 3, 4, 5]

In [3]:
type(mylist)

list

In [4]:
my_list = np.array([1,2,3,4])
my_list

array([1, 2, 3, 4])

In [5]:
type(my_list)

numpy.ndarray

In [6]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(90,100)

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [9]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
np.arange(3,1)

array([], dtype=int64)

In [11]:
np.zeros

<function numpy.zeros>

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [15]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
rand(3,2)

NameError: name 'rand' is not defined

In [21]:
andom.rand(3,2)

NameError: name 'andom' is not defined

In [22]:
np.random.rand(3,4)

array([[0.57641797, 0.651969  , 0.54435717, 0.40818058],
       [0.27184205, 0.49014074, 0.07030265, 0.32127718],
       [0.34784859, 0.30845643, 0.71628176, 0.35950332]])

In [23]:
np.random.rand(3,4)

array([[0.98396312, 0.31701722, 0.47050378, 0.74955175],
       [0.70766637, 0.13942594, 0.93078052, 0.83945155],
       [0.5757514 , 0.67774783, 0.65623649, 0.96100534]])

In [24]:
np.random.rand(5)

array([0.12509071, 0.81255289, 0.63179098, 0.49020657, 0.68010444])

In [25]:
np.random.randint(5)

0

In [26]:
np.random.randint(3,6)

4

In [27]:
np.random(3)

TypeError: 'module' object is not callable

In [28]:
np.randint(3)

AttributeError: module 'numpy' has no attribute 'randint'

In [ ]:
np.random.randint(2,20,5)

In [29]:
a = np.random.randint(2,10,2)
print(a)
                     

[2 4]


In [30]:
np.random.randint(0,10,5)

array([8, 2, 6, 4, 0], dtype=int32)

In [31]:
c = np.random.randint(0,10,5)
c

array([2, 4, 3, 1, 2], dtype=int32)

In [32]:
c=np.random.randint(0,10,5)
print(c)




[3 7 5 4 0]


In [33]:
n = np.random.randint(10,40,(8,10))
print(n)

[[31 24 21 35 22 16 26 35 24 21]
 [21 20 15 23 23 15 38 21 37 38]
 [28 28 12 38 32 28 31 31 10 26]
 [19 33 21 25 39 25 35 27 16 32]
 [25 12 18 22 34 39 35 28 27 12]
 [13 11 38 12 14 27 26 11 27 38]
 [15 21 24 26 14 12 26 32 12 16]
 [15 17 10 34 15 21 27 14 30 18]]


In [34]:
n[5]# it give the output is 5th row

array([13, 11, 38, 12, 14, 27, 26, 11, 27, 38], dtype=int32)

In [35]:
print(n[4])

[25 12 18 22 34 39 35 28 27 12]


In [36]:
print(n[4,4])

34


In [37]:
print(n[1,5])

15


In [38]:
print(n[7])

[15 17 10 34 15 21 27 14 30 18]


In [39]:
print(n[7,9])

18


In [40]:
print(n[7,-1])

18


In [41]:
print(n)

[[31 24 21 35 22 16 26 35 24 21]
 [21 20 15 23 23 15 38 21 37 38]
 [28 28 12 38 32 28 31 31 10 26]
 [19 33 21 25 39 25 35 27 16 32]
 [25 12 18 22 34 39 35 28 27 12]
 [13 11 38 12 14 27 26 11 27 38]
 [15 21 24 26 14 12 26 32 12 16]
 [15 17 10 34 15 21 27 14 30 18]]


In [42]:
print(n[1:5])

[[21 20 15 23 23 15 38 21 37 38]
 [28 28 12 38 32 28 31 31 10 26]
 [19 33 21 25 39 25 35 27 16 32]
 [25 12 18 22 34 39 35 28 27 12]]


In [43]:
print(n[::])

[[31 24 21 35 22 16 26 35 24 21]
 [21 20 15 23 23 15 38 21 37 38]
 [28 28 12 38 32 28 31 31 10 26]
 [19 33 21 25 39 25 35 27 16 32]
 [25 12 18 22 34 39 35 28 27 12]
 [13 11 38 12 14 27 26 11 27 38]
 [15 21 24 26 14 12 26 32 12 16]
 [15 17 10 34 15 21 27 14 30 18]]


In [44]:
print(n[-1])

[15 17 10 34 15 21 27 14 30 18]


In [45]:
print(n[1:7:2])

[[21 20 15 23 23 15 38 21 37 38]
 [19 33 21 25 39 25 35 27 16 32]
 [13 11 38 12 14 27 26 11 27 38]]


In [46]:
print(n[2,-4])

31


In [47]:
print(n[::-1])

[[15 17 10 34 15 21 27 14 30 18]
 [15 21 24 26 14 12 26 32 12 16]
 [13 11 38 12 14 27 26 11 27 38]
 [25 12 18 22 34 39 35 28 27 12]
 [19 33 21 25 39 25 35 27 16 32]
 [28 28 12 38 32 28 31 31 10 26]
 [21 20 15 23 23 15 38 21 37 38]
 [31 24 21 35 22 16 26 35 24 21]]


In [48]:
print(n[::-2])

[[15 17 10 34 15 21 27 14 30 18]
 [13 11 38 12 14 27 26 11 27 38]
 [19 33 21 25 39 25 35 27 16 32]
 [21 20 15 23 23 15 38 21 37 38]]


In [49]:
print(n)

[[31 24 21 35 22 16 26 35 24 21]
 [21 20 15 23 23 15 38 21 37 38]
 [28 28 12 38 32 28 31 31 10 26]
 [19 33 21 25 39 25 35 27 16 32]
 [25 12 18 22 34 39 35 28 27 12]
 [13 11 38 12 14 27 26 11 27 38]
 [15 21 24 26 14 12 26 32 12 16]
 [15 17 10 34 15 21 27 14 30 18]]


In [50]:
print(n[::1])

[[31 24 21 35 22 16 26 35 24 21]
 [21 20 15 23 23 15 38 21 37 38]
 [28 28 12 38 32 28 31 31 10 26]
 [19 33 21 25 39 25 35 27 16 32]
 [25 12 18 22 34 39 35 28 27 12]
 [13 11 38 12 14 27 26 11 27 38]
 [15 21 24 26 14 12 26 32 12 16]
 [15 17 10 34 15 21 27 14 30 18]]


In [51]:
print(n[::2])

[[31 24 21 35 22 16 26 35 24 21]
 [28 28 12 38 32 28 31 31 10 26]
 [25 12 18 22 34 39 35 28 27 12]
 [15 21 24 26 14 12 26 32 12 16]]


In [52]:
n = np.random.randint(1,10,(3,4))
print(n)

[[1 2 3 4]
 [6 6 1 6]
 [5 7 7 5]]


In [53]:
n = np.random.randint(10,40,(8,10))
print(n)

[[13 11 35 29 38 30 37 27 16 30]
 [37 36 33 39 38 37 34 19 27 10]
 [15 26 19 22 26 34 38 36 11 27]
 [27 22 28 10 36 12 20 16 12 14]
 [14 12 38 32 31 23 20 17 22 29]
 [21 14 36 32 15 13 36 22 26 20]
 [14 31 21 18 39 11 31 16 24 18]
 [34 37 13 28 11 39 24 33 17 31]]


In [54]:
print(n[1:4])

[[37 36 33 39 38 37 34 19 27 10]
 [15 26 19 22 26 34 38 36 11 27]
 [27 22 28 10 36 12 20 16 12 14]]


In [55]:
print(n)

[[13 11 35 29 38 30 37 27 16 30]
 [37 36 33 39 38 37 34 19 27 10]
 [15 26 19 22 26 34 38 36 11 27]
 [27 22 28 10 36 12 20 16 12 14]
 [14 12 38 32 31 23 20 17 22 29]
 [21 14 36 32 15 13 36 22 26 20]
 [14 31 21 18 39 11 31 16 24 18]
 [34 37 13 28 11 39 24 33 17 31]]


In [56]:
n[0,3]

np.int32(29)

In [57]:
n[3,-4]

np.int32(20)

In [58]:
np.arange(2,3)


array([2])

In [59]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [61]:
s = np.array([3,4])
s

array([3, 4])

In [62]:
s1 = np.array([1,2,3,4,5])
s1

array([1, 2, 3, 4, 5])

In [64]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [68]:
s1


array([1, 2, 3, 4, 5])

In [70]:
len(s1)

5

In [74]:
s1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [79]:
p = np.arange(1,21)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [80]:
p.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [81]:
p.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [82]:
np.random.rand(3,4)

array([[0.06334944, 0.56122277, 0.20901529, 0.10392824],
       [0.78207146, 0.73384575, 0.95144504, 0.03390163],
       [0.08322391, 0.57347177, 0.76861458, 0.79606186]])

In [87]:
np.random.randint(3,4)

3

In [89]:
np.__version__

'2.3.2'

In [94]:
n = np.random.randint(0,21,(4,5))
n

array([[12, 17, 17, 14,  5],
       [12,  9,  3, 12, 13],
       [ 0, 18, 11, 18, 16],
       [19,  9, 18,  1, 18]], dtype=int32)

In [96]:
print(n)

[[12 17 17 14  5]
 [12  9  3 12 13]
 [ 0 18 11 18 16]
 [19  9 18  1 18]]


In [98]:
n = np.full((2,3),5)
print(n)

[[5 5 5]
 [5 5 5]]


In [99]:
g = np.full((5,6),10)
g

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [103]:
h = np.random.randint(10,45,(8,10))
h

array([[27, 15, 32, 21, 39, 12, 32, 12, 43, 31],
       [24, 27, 30, 26, 38, 25, 39, 26, 26, 37],
       [31, 38, 28, 19, 28, 37, 10, 11, 19, 10],
       [33, 31, 20, 12, 32, 34, 40, 26, 22, 37],
       [25, 19, 40, 23, 13, 41, 38, 20, 21, 20],
       [11, 15, 38, 23, 18, 12, 18, 19, 22, 22],
       [41, 32, 28, 18, 13, 12, 24, 40, 18, 33],
       [31, 43, 24, 19, 43, 25, 44, 37, 40, 24]], dtype=int32)

In [105]:
h[2]

array([31, 38, 28, 19, 28, 37, 10, 11, 19, 10], dtype=int32)

In [106]:
h.shape

(8, 10)

In [111]:
#b =np.full((20,30),10)
#b

In [108]:
b.shape

(20, 30)

In [109]:
b.size

600

In [112]:
h

array([[27, 15, 32, 21, 39, 12, 32, 12, 43, 31],
       [24, 27, 30, 26, 38, 25, 39, 26, 26, 37],
       [31, 38, 28, 19, 28, 37, 10, 11, 19, 10],
       [33, 31, 20, 12, 32, 34, 40, 26, 22, 37],
       [25, 19, 40, 23, 13, 41, 38, 20, 21, 20],
       [11, 15, 38, 23, 18, 12, 18, 19, 22, 22],
       [41, 32, 28, 18, 13, 12, 24, 40, 18, 33],
       [31, 43, 24, 19, 43, 25, 44, 37, 40, 24]], dtype=int32)

In [113]:
h[0:7:2]

array([[27, 15, 32, 21, 39, 12, 32, 12, 43, 31],
       [31, 38, 28, 19, 28, 37, 10, 11, 19, 10],
       [25, 19, 40, 23, 13, 41, 38, 20, 21, 20],
       [41, 32, 28, 18, 13, 12, 24, 40, 18, 33]], dtype=int32)