In [2]:
number1 = int(input('enter the 1st number '))
number2 = int(input('Enter the 2nd number'))
number3 = int(input('enter the 3rd number'))
sum = number1+number2+number3
avg = sum/3
print(f'the average of the three number is = {avg}')

enter the 1st number  23
Enter the 2nd number 45
enter the 3rd number 56


the average of the three number is = 41.333333333333336


In [5]:
list1 = [1,2,3,4,5,6]
total = 0
for i in list1:
    total = total+i
avg = total/len(list1)
print(avg)

3.5


In [9]:
string1 = input('enter the string')
count = 0
for char in string1:
    count = count+1
print(count)

enter the string parthasarathi behera


20


In [12]:
string1 = input('enter the string')
vowels = 'AEIOUaeiou'
count = 0

for char in string1:
    count = count+1
print(count)

enter the string hello woeld


11


In [13]:
for i in range(6):
    print(' * ' *i)


 * 
 *  * 
 *  *  * 
 *  *  *  * 
 *  *  *  *  * 


In [16]:
num = int(input('enter the number'))
factor = 1
while num>0:
    factor = factor *num
    num = num-1
print(factor)

enter the number 8


40320


In [21]:
for i in range(1,11):
    sum = 0
    sum = sum+i
    i = i+1
    
print(sum)

10


In [23]:
for i in range(1,21):
    sum = 0
    sum = sum + i
print(sum)

20


In [30]:
for num in range(1,51):
    if num % 2 ==1:
        print(num)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


In [34]:
for i in range(1,21):
    if i% 3==0 or i%5==0:
        print(i)

3
5
6
9
10
12
15
18
20


In [35]:
for i in range(1,21):
    if i% 3==0 and i%5==0:
        print(i)

15


In [45]:
for i in range(1,11):
    i = i*i
    print(f'the sum of number from number is {i}')

the sum of number from number is 1
the sum of number from number is 4
the sum of number from number is 9
the sum of number from number is 16
the sum of number from number is 25
the sum of number from number is 36
the sum of number from number is 49
the sum of number from number is 64
the sum of number from number is 81
the sum of number from number is 100


In [52]:
for i in range(1,21):
    if i % 2 ==0:
        
        print(i)
    
else:
        print('out of the range')

2
4
6
8
10
12
14
16
18
20
out of the range


In [54]:
for i in range(1,21):
    if i % 2 ==0:
        continue
        
    print(i)
    
else:
        print('out of the range')

1
3
5
7
9
11
13
15
17
19
out of the range


In [56]:
for i in range(1,20):
    if i %4 ==0:
        continue
    print(i)

1
2
3
5
6
7
9
10
11
13
14
15
17
18
19


In [58]:
for i in range(1,28):
    if i ==3:
        
        continue
    print(i)

1
2
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [59]:
for i in range(1,28):
    if i ==3:
        
        break
    print(i)

1
2


In [60]:
for i in range(1,11):
    if i >0:
        print(i)

1
2
3
4
5
6
7
8
9
10


In [64]:
for i in range(10):
    sum = 0 
    sum = sum +i
    print (f'the sum of number is {sum}')

the sum of number is 0
the sum of number is 1
the sum of number is 2
the sum of number is 3
the sum of number is 4
the sum of number is 5
the sum of number is 6
the sum of number is 7
the sum of number is 8
the sum of number is 9


In [1]:
num = int(input('enter the number'))
if num %2 ==0:
    print('even')
else:
    print('odd')

enter the number 80


even


In [2]:
age = int(input('enter the age'))
if age >= 18:
    print('eligible for vote')
else:
    print('not eligible to vote')


enter the age 56


eligible for vote


In [3]:
year = int(input('enter the year'))
if year % 4 ==0:
    print('leap year')
else:
    print('not leap year')

enter the year 2000


leap year


In [5]:
number = int(input('enter the number '))
if number > 0 :
    print('+ve')
elif number < 0:
    print('-ve')
else:
    print('zero')

enter the number  -2


-ve


In [8]:
num1 = int(input('enter the num1'))
num2 = int(input('enter the num2'))
if num1<num2:
    print('gratter')
else:
    print('not gratter')


enter the num1 23
enter the num2 45


gratter


In [10]:
num = int(input('emter the number'))
if num % 5==0:
    print('number  is multiplication of 5')
else:
    print('not multiplication by 5')

emter the number 56


not multiplication by 5


In [12]:
str = input('enter the string').lower()
if str in 'aeiou':
    print('vowel')
else:
    print('consonent')

enter the string apple


consonent


In [12]:
count = 0
for i in range(3):
    for j in range(3):
        count = count+1
        if count % 2==0:
            break
print(count)

6


In [13]:
t = (1,[2,3])
t[1] = t[1]+[4,5]
print(t)

TypeError: 'tuple' object does not support item assignment

In [14]:
s = 'ABCDEFG'
print(s[10:2:-2])

GE


In [15]:
x = True + 2* False
print(x == 1)

True


In [16]:
lst = [i for i in range(5) if i %2 ==0 if i>1]
print(lst)

[2, 4]


In [18]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1],[2],[3]])
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [19]:
import pandas as pd
df = pd.DataFrame({'A':[1,2,3]})
df

A
0  1
1  2
2  3

In [20]:
import pandas as pd
df = pd.DataFrame({'A':[1,2,3]})
df['A'] += df['A']>1
print(df)

   A
0  1
1  3
2  4


In [21]:
i = 1
while i<10:
    i *= 2
    if i>5:
        break
else:
    print('done')
print(i)

8


In [22]:
lst = [[0]*2]*2
lst[1][1] = 5
print(lst)

[[0, 5], [0, 5]]


In [26]:
lst =[[0]*2] * 3
lst[1][1] = 5
lst

[[0, 5], [0, 5], [0, 5]]

In [27]:
x = 2+3*4**2//8%3
x

2

In [28]:
a = [1,2,3,4]
b = a
b.append(5)
print(a)

[1, 2, 3, 4, 5]


In [29]:
a = [1,2,3,4]
b = a
b.append(5)
print(b)

[1, 2, 3, 4, 5]


In [30]:
a = [1,2]; b = a ; b+=[3]
print(a)

[1, 2, 3]


In [31]:
s1 = {1,2,3}
s2 = {2,3,4}
s1^s2

{1, 4}

In [32]:
s = {1,2,3}
s.discard(5)
s.remove(3)
s

{1, 2}

In [33]:
lst = [0,1,2,3,4,5]
print(lst[-2:-5:-1])

[4, 3, 2]


In [34]:
lst = [0,1,2,3,4,5]
print(lst[-2:-5])

[]


In [35]:
arr = np.arr([1,2,3],dtype = float)
arr[0] = '4'
arr

AttributeError: module 'numpy' has no attribute 'arr'

In [36]:
int('123')

123

In [37]:
float('12.3')

12.3

In [38]:
str(123)

'123'

In [40]:
int('12.3')

ValueError: invalid literal for int() with base 10: '12.3'

In [41]:
'abc'*3

'abcabcabc'

In [42]:
'abc'*3 + '3'*2

'abcabcabc33'

In [44]:
4//2

2

Linear Algebra Function

In [46]:
# create a matrix
m = np.array([[1,2],[3,4]])
m

array([[1, 2],
       [3, 4]])

In [48]:
determinent = np.linalg.det(m)
determinent

np.float64(-2.0000000000000004)

In [50]:
inverse = np.linalg.inv(m)
inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Random Sampling Function

In [52]:
arr = np.random.rand(4)
arr

array([0.15915697, 0.93628118, 0.8161081 , 0.50644675])

In [56]:
arr = np.random.rand(12)

In [57]:
arr

array([0.93496661, 0.92653904, 0.30538714, 0.21423359, 0.86993068,
       0.737426  , 0.21186371, 0.72400206, 0.64965375, 0.48989649,
       0.04680576, 0.90410315])

In [63]:
arr = np.random.randint(12,size = 5)
arr

array([ 3,  0,  3, 10, 11], dtype=int32)

In [64]:
arr = np.random.rand(5)
arr

array([0.67881636, 0.23940236, 0.61005493, 0.35101637, 0.75858765])

In [66]:
arr = np.random.rand(5)
arr

array([0.44358553, 0.13009398, 0.26938253, 0.92258108, 0.98484345])

In [67]:
arr = np.random.randint(5,15,size=5)
arr

array([12,  5, 11,  6,  7], dtype=int32)