In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import re
import math

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Creating serise from numpy array
v = np.array([1,2,3,4,5,6])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
s1.dtype

dtype('int64')

In [5]:
s1.item

<bound method IndexOpsMixin.item of 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64>

In [6]:
s1.nbytes

48

In [7]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
s1.shape # shape of serise

(6,)

In [9]:
s1.ndim #give dimenson of the serise

1

In [10]:
len(s1)

6

In [11]:
p = s1.count()
print(p)

6


In [12]:
p1 = s1.size
print(p1)

6


In [13]:
v1 = np.array([11,22,33,44,55,66])
s2 = pd.Series(v1)
(s2)

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

In [14]:
s2.dtype

dtype('int64')

In [15]:
s2.dtypes

dtype('int64')

In [16]:
s2.ndim

1

In [17]:
s2.shape

(6,)

In [18]:
s2.size

6

In [19]:
s2.count()

np.int64(6)

In [20]:
# creating serise from list
s0 = pd.Series([1,2,3,4],index=['a','b','c','d'])
s0

a    1
b    2
c    3
d    4
dtype: int64

In [21]:
p1 = np.array([10,20,30,40])
a1 = pd.Series(p1,index= ['a','b','c','d'])
a1

a    10
b    20
c    30
d    40
dtype: int64

In [22]:
s0

a    1
b    2
c    3
d    4
dtype: int64

In [23]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [24]:
# Modifying index in serise
s1.index = ['1st','2nd','3rd','4th','5th','6th']
s1

1st    1
2nd    2
3rd    3
4th    4
5th    5
6th    6
dtype: int64

In [25]:
s2

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

In [26]:
s2.index = ['partha','gudu','prakash','chitta','ramesh','rudr']
s2

partha     11
gudu       22
prakash    33
chitta     44
ramesh     55
rudr       66
dtype: int64

In [27]:
# creating Serise using randome and range fuction 
v2 = np.random.random(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
v2

array([0.74433293, 0.61977799, 0.7096556 , 0.58435916, 0.9611704 ,
       0.48593765, 0.60749172, 0.77008379, 0.92651279, 0.78655443])

In [28]:
# creating Serise using randome and range fuction 
v2 = np.random.random(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
ind2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# creating Serise using randome and range fuction 
v2 = np.random.random(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
s

0    0.894821
1    0.441283
2    0.197766
3    0.143007
4    0.150858
5    0.164684
6    0.331593
7    0.970741
8    0.410253
9    0.380552
dtype: float64

In [30]:
# creating Serise using randome and range fuction 
v2 = np.random.random(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
print(v2)
print(ind2)
print(s)

[0.48660563 0.9480763  0.3628231  0.51811204 0.54148048 0.04455489
 0.06476164 0.37377981 0.66969106 0.7815424 ]
[0 1 2 3 4 5 6 7 8 9]
0    0.486606
1    0.948076
2    0.362823
3    0.518112
4    0.541480
5    0.044555
6    0.064762
7    0.373780
8    0.669691
9    0.781542
dtype: float64


In [31]:
# creating Serise using randome and range fuction 
v2 = np.random.rand(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
v2

array([0.50755434, 0.77440022, 0.86666488, 0.90169874, 0.86051871,
       0.01471151, 0.57016071, 0.12905374, 0.6673408 , 0.83422704])

In [32]:
# creating Serise using randome and range fuction 
v2 = np.random.randint(10,60)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
v2

20

In [33]:
# creating Serise using randome and range fuction 
v2 = np.random.rand(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
v2

array([0.23278768, 0.95925337, 0.59520227, 0.180134  , 0.26499201,
       0.39333728, 0.30720863, 0.65564247, 0.44852959, 0.83306243])

In [34]:

aa = np.arange(0,5)
aa

array([0, 1, 2, 3, 4])

In [35]:
# creating Serise using randome and range fuction 
v2 = np.random.random_integers(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
print(v2)
print(ind2)
print(s)

6
[0 1 2 3 4 5 6 7 8 9]
0    6
1    6
2    6
3    6
4    6
5    6
6    6
7    6
8    6
9    6
dtype: int32


In [36]:
# creating Serise from dictionary
dict1 = {'a1':10, 'a2':20, 'a3':30, 'a4':40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [37]:
set1 = {12,13,14,17,47}
s4 = pd.Series(set1) # set is onordered so set is not used in pandas
s4

TypeError: 'set' type is unordered

In [38]:
vegetable = 'potato','tomato','cocomber','carret'
r = pd.Series(vegetable)
r

0      potato
1      tomato
2    cocomber
3      carret
dtype: object

In [39]:
# creating Serise from dictionary
dict1 = {'a1':10, 'a2':20, 'a3':30, 'a4':40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [40]:
r = pd.Series(66)
print(r)

0    66
dtype: int64


In [41]:
pd.Series(33,index=[1,2,3,4,5,6])

1    33
2    33
3    33
4    33
5    33
6    33
dtype: int64

In [42]:
s

0    6
1    6
2    6
3    6
4    6
5    6
6    6
7    6
8    6
9    6
dtype: int32

In [43]:
# creating Serise using randome and range fuction 
v2 = np.random.random(10)
ind2 = np.arange(0,10)
a = pd.Series(v2,ind2)
print(v2)
print(ind2)
print(a)

[0.88587086 0.30073216 0.66166685 0.32618496 0.8208876  0.39281166
 0.38177938 0.5362901  0.00926864 0.57032694]
[0 1 2 3 4 5 6 7 8 9]
0    0.885871
1    0.300732
2    0.661667
3    0.326185
4    0.820888
5    0.392812
6    0.381779
7    0.536290
8    0.009269
9    0.570327
dtype: float64


In [44]:
a

0    0.885871
1    0.300732
2    0.661667
3    0.326185
4    0.820888
5    0.392812
6    0.381779
7    0.536290
8    0.009269
9    0.570327
dtype: float64

In [45]:
a[:]

0    0.885871
1    0.300732
2    0.661667
3    0.326185
4    0.820888
5    0.392812
6    0.381779
7    0.536290
8    0.009269
9    0.570327
dtype: float64

In [46]:
a[:3] # it give first three element

0    0.885871
1    0.300732
2    0.661667
dtype: float64

In [47]:
a[3:] # it give the 3rd index element to the last element

3    0.326185
4    0.820888
5    0.392812
6    0.381779
7    0.536290
8    0.009269
9    0.570327
dtype: float64

In [48]:
a[:-1]

0    0.885871
1    0.300732
2    0.661667
3    0.326185
4    0.820888
5    0.392812
6    0.381779
7    0.536290
8    0.009269
dtype: float64

In [49]:
a[0]

np.float64(0.8858708613470033)

In [50]:
a[8]

np.float64(0.00926863885237006)

In [51]:
a[:-2]

0    0.885871
1    0.300732
2    0.661667
3    0.326185
4    0.820888
5    0.392812
6    0.381779
7    0.536290
dtype: float64

In [52]:
a

0    0.885871
1    0.300732
2    0.661667
3    0.326185
4    0.820888
5    0.392812
6    0.381779
7    0.536290
8    0.009269
9    0.570327
dtype: float64

In [53]:
a[-2:]

8    0.009269
9    0.570327
dtype: float64

In [54]:
a[-3:-1]

7    0.536290
8    0.009269
dtype: float64

In [55]:
a[-5:-1]

5    0.392812
6    0.381779
7    0.536290
8    0.009269
dtype: float64

Append Serise

In [56]:
s2

partha     11
gudu       22
prakash    33
chitta     44
ramesh     55
rudr       66
dtype: int64

In [57]:
s1

1st    1
2nd    2
3rd    3
4th    4
5th    5
6th    6
dtype: int64

In [58]:
x = s1.copy()


In [59]:
x

1st    1
2nd    2
3rd    3
4th    4
5th    5
6th    6
dtype: int64

In [60]:
s1

1st    1
2nd    2
3rd    3
4th    4
5th    5
6th    6
dtype: int64

In [61]:
print(id(x))
print(id(s1))

2871199340624
2873294615088


In [62]:
x = s1
print(id(x))
print(id(s1))

2873294615088
2873294615088


In [63]:
s2

partha     11
gudu       22
prakash    33
chitta     44
ramesh     55
rudr       66
dtype: int64

In [64]:
v11 = np.array([10,20,30,40,50])
s11 = pd.Series(v11)
s11

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [65]:
s12 = s11.add_prefix(s2)
print(s12)

partha     11\ngudu       22\nprakash    33\nchitta     44\nramesh     55\nrudr       66\ndtype: int640    10
partha     11\ngudu       22\nprakash    33\nchitta     44\nramesh     55\nrudr       66\ndtype: int641    20
partha     11\ngudu       22\nprakash    33\nchitta     44\nramesh     55\nrudr       66\ndtype: int642    30
partha     11\ngudu       22\nprakash    33\nchitta     44\nramesh     55\nrudr       66\ndtype: int643    40
partha     11\ngudu       22\nprakash    33\nchitta     44\nramesh     55\nrudr       66\ndtype: int644    50
dtype: int64


In [66]:
s2

partha     11
gudu       22
prakash    33
chitta     44
ramesh     55
rudr       66
dtype: int64

In [67]:
s1

1st    1
2nd    2
3rd    3
4th    4
5th    5
6th    6
dtype: int64

In [68]:
s12 = s11.add_prefix(s1)
print(s12)

1st    1\n2nd    2\n3rd    3\n4th    4\n5th    5\n6th    6\ndtype: int640    10
1st    1\n2nd    2\n3rd    3\n4th    4\n5th    5\n6th    6\ndtype: int641    20
1st    1\n2nd    2\n3rd    3\n4th    4\n5th    5\n6th    6\ndtype: int642    30
1st    1\n2nd    2\n3rd    3\n4th    4\n5th    5\n6th    6\ndtype: int643    40
1st    1\n2nd    2\n3rd    3\n4th    4\n5th    5\n6th    6\ndtype: int644    50
dtype: int64


In [69]:
s11

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [70]:
s11.drop(3,inplace=False)

0    10
1    20
2    30
4    50
dtype: int64

In [71]:
s11

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [72]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [73]:
s3.describe()

count     4.000000
mean     25.000000
std      12.909944
min      10.000000
25%      17.500000
50%      25.000000
75%      32.500000
max      40.000000
dtype: float64

In [74]:
s3.drop('a1')

a2    20
a3    30
a4    40
dtype: int64

In [75]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [76]:
s3.drop(a4,inplace=True)
s3

NameError: name 'a4' is not defined

In [ ]:
s11.drop(3,inplace=True)
s11

In [77]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [78]:
s11

0    10
1    20
2    30
3    40
4    50
dtype: int64

Operation on serise

In [79]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1,s2

(0    10
 1    20
 2    30
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [80]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
print(s2)
print(s1)

0    1
1    2
2    3
dtype: int64
0    10
1    20
2    30
dtype: int64


In [81]:
s1.add(s2)

0    11
1    22
2    33
dtype: int64

In [82]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int64

In [83]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int64

In [84]:
s1,s2

(0    10
 1    20
 2    30
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [85]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [86]:
b1 = np.array([20,21,22,23,24])
c1 = np.array([5,6,7,8,9])
d1 = pd.Series(b1)
d2 = pd.Series(c1)
d1,d2

(0    20
 1    21
 2    22
 3    23
 4    24
 dtype: int64,
 0    5
 1    6
 2    7
 3    8
 4    9
 dtype: int64)

In [87]:
d1.add(d2)

0    25
1    27
2    29
3    31
4    33
dtype: int64

In [88]:
d1,d2

(0    20
 1    21
 2    22
 3    23
 4    24
 dtype: int64,
 0    5
 1    6
 2    7
 3    8
 4    9
 dtype: int64)

In [89]:
d1.sub(d2)

0    15
1    15
2    15
3    15
4    15
dtype: int64

In [90]:
d2.sub(d1)

0   -15
1   -15
2   -15
3   -15
4   -15
dtype: int64

In [91]:
d1.multiply(d2)

0    100
1    126
2    154
3    184
4    216
dtype: int64

In [92]:
d1.divide(d2)

0    4.000000
1    3.500000
2    3.142857
3    2.875000
4    2.666667
dtype: float64

In [93]:
s1,s2

(0    10
 1    20
 2    30
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [94]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int64

In [95]:
s1.max()

30

In [96]:
s2.min()

1

In [97]:
d1.max()

24

In [98]:
d2.min

<bound method Series.min of 0    5
1    6
2    7
3    8
4    9
dtype: int64>

In [99]:
d1,d2

(0    20
 1    21
 2    22
 3    23
 4    24
 dtype: int64,
 0    5
 1    6
 2    7
 3    8
 4    9
 dtype: int64)

In [100]:
s1,s2

(0    10
 1    20
 2    30
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [101]:
s1.mean() # here mean() == average

np.float64(20.0)

In [102]:
s2.mean()

np.float64(2.0)

In [103]:
d1.mean()

np.float64(22.0)

In [104]:
d2.mean()

np.float64(7.0)

In [105]:
s1.median()

20.0

In [106]:
e = np.array([1,2,3,4,9])
e1 = pd.Series(e)
e1

0    1
1    2
2    3
3    4
4    9
dtype: int64

In [107]:
e1.median()

3.0

In [108]:
s1

0    10
1    20
2    30
dtype: int64

In [109]:
s1.std()

10.0

In [110]:
s1==s2

0    False
1    False
2    False
dtype: bool

In [111]:
s1.equals(s2)

False

In [112]:
s1!=s2

0    True
1    True
2    True
dtype: bool

In [113]:
s5 = pd.Series([1,1,2,2,3,3,3,4,4])
s5

0    1
1    1
2    2
3    2
4    3
5    3
6    3
7    4
8    4
dtype: int64

In [114]:
s5.value_counts()

3    3
1    2
2    2
4    2
Name: count, dtype: int64

DataFrame
== Create DataFrame

In [115]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [116]:
# create dataframe using list
lang = ['java','clanguage','python','c++']
df = pd.Series(lang)
df

0         java
1    clanguage
2       python
3          c++
dtype: object

In [118]:
lang = ['java','python','c','c++'] # when we use DataFrame() program cannot give dtype
df = pd.DataFrame(lang)
df

0
0    java
1  python
2       c
3     c++

In [119]:
# add column in the Dataframe
rating = [1,2,3,4]
df[1] = rating
df

0  1
0    java  1
1  python  2
2       c  3
3     c++  4

In [125]:
#rating = [5,6,7,8]
#df[2] = rating
#df

In [126]:
#addcolumn = [10,11,12,13]
#df[3] = addcolumn
#df

In [127]:
df.columns

RangeIndex(start=0, stop=4, step=1)

In [140]:
df.columns = ['Language','Rating1']

In [141]:
df

Language  Rating1
0     java        1
1   python        2
2        c        3
3      c++        4

In [136]:
lang1 = ['java' , 'python','c','c++']
df1 = pd.DataFrame(lang1)
df1

0
0    java
1  python
2       c
3     c++

In [137]:
rating  = [1,2,3,4]
df1[1] = rating
df1

0  1
0    java  1
1  python  2
2       c  3
3     c++  4

In [138]:
df1.columns = ['Language','Rating']
df1

Language  Rating
0     java       1
1   python       2
2        c       3
3      c++       4

In [142]:
df

Language  Rating1
0     java        1
1   python        2
2        c        3
3      c++        4

In [143]:
df1

Language  Rating
0     java       1
1   python       2
2        c       3
3      c++       4

In [146]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
data

[{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]

In [148]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df2 = pd.DataFrame(data)
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [149]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df3 = pd.DataFrame(data,index=['row1','row2'],columns=['a','b'])
df3


a   b
row1  1   2
row2  5  10

In [150]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df4 = pd.DataFrame(data,index=['row1','row2'],columns=['a','b','c'])

df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [151]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df5 = pd.DataFrame(data,index=['row1','row2'],columns=['a','b','c','d'])

df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [152]:
#creating dataframe from dict of string
dict = {'A' : pd.Series([1,2,3], index=['a','b','c']),
        'B' : pd.Series([1,2,3,4], index=['a','b','c','d'])}
df1 = pd.DataFrame(dict)
df1

A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [153]:
dates = pd.date_range(start = '2020-01-20', end = '2020-01-26')
dates

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [154]:
dates = pd.date_range(start = '20-01-2020', end = '26-01-2020')
dates

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [157]:
dates.dtype

dtype('<M8[ns]')

In [158]:
dates = pd.date_range('today',periods = 6)
dates

DatetimeIndex(['2025-08-20 17:56:08.524578', '2025-08-21 17:56:08.524578',
               '2025-08-22 17:56:08.524578', '2025-08-23 17:56:08.524578',
               '2025-08-24 17:56:08.524578', '2025-08-25 17:56:08.524578'],
              dtype='datetime64[ns]', freq='D')

In [159]:
dates = pd.date_range(start = '20-01-2020',periods = 7)
dates

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [160]:
M = np.random.random((5,5))
M

array([[0.23947233, 0.41004757, 0.7343337 , 0.50607744, 0.32030511],
       [0.76432035, 0.98261409, 0.68434586, 0.93665522, 0.32079869],
       [0.68949781, 0.25135973, 0.92498466, 0.21642492, 0.35554308],
       [0.12494354, 0.07425566, 0.40642058, 0.94876175, 0.5278151 ],
       [0.00587455, 0.55746624, 0.08530305, 0.20044351, 0.38741713]])